apiVersion: v1
kind: Service
metadata:
  name: whoami-headless
spec:
  type: ClusterIP
  clusterIP: "None"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: whoami
    #role: frontend
