---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-app
spec:
  selector:
    matchLabels:
      app: whoami
  replicas: 3
  template:
    metadata:
      labels:
        app: whoami
        role: frontend
        dmz: 'true'
    spec:
      containers:
      - name: whoami-container
        image: "containous/whoami"
        ports:
        - containerPort: 80
